// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idampxfbqakcdamqxgqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkYW1weGZicWFrY2RhbXF4Z3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MjIwMzMsImV4cCI6MjA4NTQ5ODAzM30.Rvd4TRq97Ee4-cooiBLJAzFQcatDWxCWQQb1OxGuxLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});